# -*- coding: utf-8 -*-
"""pexels api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vA-xqWtQfoFyj-5j7ikFK-bNmJDE28hI
"""

!pip install -q pexels_api
!pip install -q PyPexels

from pypexels import PyPexels
# add your api key
api_key = ''

# instantiate PyPexels object
py_pexel = PyPexels(api_key=api_key)

# create a list for the results
empty = []


search_results = py_pexel.search(query='bears', per_page=6)
while True:
    for photo in search_results.entries:
        print(photo.id, photo.photographer, photo.url)
        empty.append(photo.url)
        print(empty)
    if not search_results.has_next:
        break
    search_results = search_results.get_next_page()